In [26]:
#Step 1: Importing the Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [27]:
#Step 2: Importing the dataset
dataset = pd.read_csv("iris.csv")

In [28]:
#Step 3:Describe dataset,See dimention and Exlpore dataset
dataset.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [29]:
dataset.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [30]:
dataset.shape

(150, 6)

In [31]:
X = dataset.iloc[:,:4].values
X

array([[  1. ,   5.1,   3.5,   1.4],
       [  2. ,   4.9,   3. ,   1.4],
       [  3. ,   4.7,   3.2,   1.3],
       [  4. ,   4.6,   3.1,   1.5],
       [  5. ,   5. ,   3.6,   1.4],
       [  6. ,   5.4,   3.9,   1.7],
       [  7. ,   4.6,   3.4,   1.4],
       [  8. ,   5. ,   3.4,   1.5],
       [  9. ,   4.4,   2.9,   1.4],
       [ 10. ,   4.9,   3.1,   1.5],
       [ 11. ,   5.4,   3.7,   1.5],
       [ 12. ,   4.8,   3.4,   1.6],
       [ 13. ,   4.8,   3. ,   1.4],
       [ 14. ,   4.3,   3. ,   1.1],
       [ 15. ,   5.8,   4. ,   1.2],
       [ 16. ,   5.7,   4.4,   1.5],
       [ 17. ,   5.4,   3.9,   1.3],
       [ 18. ,   5.1,   3.5,   1.4],
       [ 19. ,   5.7,   3.8,   1.7],
       [ 20. ,   5.1,   3.8,   1.5],
       [ 21. ,   5.4,   3.4,   1.7],
       [ 22. ,   5.1,   3.7,   1.5],
       [ 23. ,   4.6,   3.6,   1. ],
       [ 24. ,   5.1,   3.3,   1.7],
       [ 25. ,   4.8,   3.4,   1.9],
       [ 26. ,   5. ,   3. ,   1.6],
       [ 27. ,   5. ,   3.4,   1.6],
 

In [32]:
y = dataset['Species'].values
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [33]:
#Step 4: Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [34]:
#Step 5: Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train

array([[ 1.52881469,  1.38721311,  0.17498533,  0.97655091],
       [ 0.37127794, -0.3945285 , -1.10539513,  0.39091318],
       [ 0.60750993,  0.62360956,  0.68713751,  1.32793355],
       [-0.8571284 , -1.79446834, -0.08109076, -1.42456377],
       [-0.55002681,  0.75087682,  0.43106142,  0.44947696],
       [ 1.1980899 ,  1.76901489,  0.43106142,  1.32793355],
       [ 1.41069869,  0.36907505, -1.10539513,  1.09367846],
       [-0.31379482,  0.11454053, -0.08109076,  0.27378564],
       [ 0.39490114,  0.36907505, -0.08109076,  0.50804073],
       [ 1.76504667,  0.11454053, -0.08109076,  0.80085959],
       [-1.51857797, -0.52179576,  1.71144188, -1.30743623],
       [-0.40828762, -1.15813205, -1.61754731, -0.25328832],
       [-0.71538921, -0.90359753,  1.96751797, -1.07318114],
       [-0.7626356 , -1.79446834,  0.43106142, -1.42456377],
       [-1.49495477, -1.28539931,  0.94321361, -1.24887245],
       [-0.33741802, -1.03086479, -2.64185168, -0.13616077],
       [ 0.86736512,  0.

In [35]:
X_test

array([[-1.54220116, -1.15813205,  0.17498533, -1.30743623],
       [-1.42408517, -0.01272673,  2.47967016, -1.48312755],
       [-0.07756284,  0.36907505, -0.59324295,  0.15665809],
       [-1.09336039, -0.77633027,  0.94321361, -1.366     ],
       [ 1.3162059 ,  2.0235494 , -0.59324295,  1.38649732],
       [-1.32959238, -0.13999398,  1.96751797, -1.19030868],
       [ 0.98548111,  0.87814408, -0.08109076,  1.03511468],
       [-1.56582436, -1.79446834, -0.33716685, -1.366     ],
       [ 0.51301713, -0.13999398, -0.33716685,  0.27378564],
       [-0.29017163,  0.24180779, -2.1296995 ,  0.15665809],
       [ 1.33982909,  2.65988569,  1.96751797,  1.56218864],
       [ 1.2925827 ,  1.76901489, -0.08109076,  1.210806  ],
       [ 0.65475633,  1.64174763, -0.08109076,  1.26936978],
       [-1.35321557, -0.90359753,  1.1992897 , -1.366     ],
       [ 1.45794509,  0.62360956,  0.94321361,  1.09367846],
       [-0.12480923, -0.26726124, -1.36147122,  0.09809432],
       [-0.19567883, -0.

In [36]:
#Step 6: Training the Naive Bayes Classification model on the Training Set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [37]:
y_pred = classifier.predict(X_test) 
y_pred


array(['Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa'], dtype='<U15')

In [38]:
#Step 7: Confusion Matrix and Accuracy
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[11,  0,  0],
       [ 0,  6,  0],
       [ 0,  2, 11]])

In [39]:
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(y_test, y_pred))
Accuracy :  1.0

Accuracy :  0.9333333333333333


In [40]:
#Step 8: Comparing the Real Values with Predicted Values


df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
df

Real Values Predicted Values
0       Iris-setosa      Iris-setosa
1       Iris-setosa      Iris-setosa
2   Iris-versicolor  Iris-versicolor
3       Iris-setosa      Iris-setosa
4    Iris-virginica   Iris-virginica
5       Iris-setosa      Iris-setosa
6    Iris-virginica   Iris-virginica
7       Iris-setosa      Iris-setosa
8   Iris-versicolor  Iris-versicolor
9   Iris-versicolor  Iris-versicolor
10   Iris-virginica   Iris-virginica
11   Iris-virginica   Iris-virginica
12   Iris-virginica   Iris-virginica
13      Iris-setosa      Iris-setosa
14   Iris-virginica   Iris-virginica
15  Iris-versicolor  Iris-versicolor
16  Iris-versicolor  Iris-versicolor
17      Iris-setosa      Iris-setosa
18   Iris-virginica  Iris-versicolor
19   Iris-virginica   Iris-virginica
20   Iris-virginica  Iris-versicolor
21      Iris-setosa      Iris-setosa
22      Iris-setosa      Iris-setosa
23  Iris-versicolor  Iris-versicolor
24   Iris-virginica   Iris-virginica
25   Iris-virginica   Iris-virginica
26      Iris-setosa      Iris-setosa
27   Iris-virginica   Iris-virginica
28   Iris-virginica   Iris-virginica
29      Iris-setosa      Iris-setosa

In [41]:
from sklearn.metrics import accuracy_score, precision_score, recall_score

# Calculate metrics
accuracy = accuracy_score(y_test, y_pred)
error_rate = 1 - accuracy
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')

# Print metrics
print("Confusion Matrix:\n", cm)
print(f"Accuracy: {accuracy:.2f}")
print(f"Error Rate: {error_rate:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")

Confusion Matrix:
 [[11  0  0]
 [ 0  6  0]
 [ 0  2 11]]
Accuracy: 0.93
Error Rate: 0.07
Precision: 0.95
Recall: 0.93
