In [28]:
#Step 1: Importing the Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score


In [29]:
#Step 2: Importing the dataset
dataset = pd.read_csv('https://raw.githubusercontent.com/mk-gurucharan/Classification/master/IrisDataset.csv')

In [30]:
#Step 3:Describe dataset,See dimention and Exlpore dataset
dataset.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [31]:
dataset.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [32]:
dataset.shape

(150, 5)

In [33]:
X = dataset.iloc[:,:4].values
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [34]:
y = dataset['species'].values
y


array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [35]:
#Step 4: Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [36]:
#Step 5: Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train

array([[ 1.44153739,  0.36924326,  0.49127713,  0.22557794],
       [ 0.55638285,  0.59764115,  0.49127713,  0.49627146],
       [-1.08747558,  1.05443693, -1.49132495, -1.26323645],
       [-0.20232104, -0.54434831,  0.37465348,  0.09023118],
       [-0.20232104, -0.54434831,  0.14140618,  0.09023118],
       [-0.58167298, -0.08755253,  0.37465348,  0.3609247 ],
       [-1.21392623, -0.08755253, -1.43301312, -1.39858321],
       [-1.08747558, -1.68633776, -0.32508843, -0.31580911],
       [ 0.05058026, -0.08755253,  0.72452444,  0.76696499],
       [-0.07587039, -0.54434831,  0.72452444,  1.57904557],
       [-0.83457428,  2.42482428, -1.3747013 , -1.53392998],
       [ 1.1886361 , -0.08755253,  0.95777174,  1.17300528],
       [-0.96102493,  1.05443693, -1.43301312, -1.39858321],
       [-0.58167298,  1.51123271, -1.3747013 , -1.39858321],
       [ 0.9357348 , -0.08755253,  0.31634166,  0.22557794],
       [ 0.05058026,  0.36924326,  0.54958896,  0.76696499],
       [-1.08747558, -2.

In [37]:
X_test

array([[-0.96102493,  1.73963061, -1.3747013 , -1.26323645],
       [ 2.32669194, -0.54434831,  1.65751365,  1.03765851],
       [-0.20232104, -1.22954198,  0.66621261,  1.03765851],
       [ 1.06218545,  0.14084537,  1.01608357,  1.57904557],
       [ 1.06218545, -0.08755253,  0.78283626,  1.4436988 ],
       [-1.84617947,  0.36924326, -1.49132495, -1.39858321],
       [-0.96102493,  1.51123271, -1.3747013 , -1.12788969],
       [-1.08747558,  1.05443693, -1.31638947, -0.85719616],
       [ 1.06218545, -0.08755253,  0.66621261,  0.63161823],
       [-1.08747558, -0.08755253, -1.31638947, -1.39858321],
       [-1.21392623,  0.14084537, -1.3747013 , -1.53392998],
       [-1.97263012, -0.08755253, -1.6079486 , -1.53392998],
       [-1.59327817,  0.36924326, -1.43301312, -1.39858321],
       [-0.20232104,  1.73963061, -1.25807764, -1.26323645],
       [ 1.69443869, -0.08755253,  1.13270722,  0.49627146],
       [ 1.31508675,  0.14084537,  0.60790079,  0.3609247 ],
       [ 1.06218545,  0.

In [38]:
#Step 6: Training the Naive Bayes Classification model on the Training Set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [39]:
y_pred = classifier.predict(X_test) 
y_pred


array(['setosa', 'virginica', 'virginica', 'virginica', 'virginica',
       'setosa', 'setosa', 'setosa', 'virginica', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'virginica', 'virginica',
       'virginica', 'virginica', 'versicolor', 'setosa', 'setosa',
       'setosa', 'versicolor', 'virginica', 'setosa', 'versicolor',
       'versicolor', 'virginica', 'setosa', 'versicolor'], dtype='<U10')

In [40]:
#Step 7: Confusion Matrix and Accuracy
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[14,  0,  0],
       [ 0,  5,  2],
       [ 0,  0,  9]])

In [41]:
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(y_test, y_pred))
Accuracy :  1.0

Accuracy :  0.9333333333333333


In [42]:
#Step 8: Comparing the Real Values with Predicted Values


df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
df

Real Values Predicted Values
0       setosa           setosa
1    virginica        virginica
2    virginica        virginica
3    virginica        virginica
4    virginica        virginica
5       setosa           setosa
6       setosa           setosa
7       setosa           setosa
8   versicolor        virginica
9       setosa           setosa
10      setosa           setosa
11      setosa           setosa
12      setosa           setosa
13      setosa           setosa
14   virginica        virginica
15  versicolor        virginica
16   virginica        virginica
17   virginica        virginica
18  versicolor       versicolor
19      setosa           setosa
20      setosa           setosa
21      setosa           setosa
22  versicolor       versicolor
23   virginica        virginica
24      setosa           setosa
25  versicolor       versicolor
26  versicolor       versicolor
27   virginica        virginica
28      setosa           setosa
29  versicolor       versicolor

In [43]:
print("Confusion Matrix:\n", cm)
print(f"Accuracy: {accuracy:.2f}")
print(f"Error Rate: {error_rate:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")

Confusion Matrix:
 [[14  0  0]
 [ 0  5  2]
 [ 0  0  9]]
Accuracy: 1.00
Error Rate: 0.00
Precision: 1.00
Recall: 1.00
