In [1]:
#Step 1: Importing the Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#Step 2: Importing the dataset
dataset = pd.read_csv('https://raw.githubusercontent.com/mk-gurucharan/Classification/master/IrisDataset.csv')

In [3]:
#Step 3:Describe dataset,See dimention and Exlpore dataset
dataset.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [4]:
dataset.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
dataset.shape

(150, 5)

In [14]:
X = dataset.iloc[:,:4].values
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [12]:
y = dataset['species'].values
y


array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [15]:
#Step 4: Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [16]:
#Step 5: Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train

array([[-0.11388702, -1.25192745,  0.71300843,  1.04767774],
       [-0.23590884, -0.06150515,  0.19235319,  0.12228415],
       [ 1.22835291, -0.53767407,  0.59730726,  0.25448324],
       [-0.72399609,  2.5574239 , -1.31176196, -1.46410485],
       [-0.47995246,  2.08125498, -1.19606079, -1.0675076 ],
       [ 1.35037472,  0.17657931,  0.65515785,  0.38668232],
       [ 1.1063311 ,  0.65274823,  1.1179625 ,  1.17987682],
       [-0.96803971,  1.36700161, -1.36961254, -1.33190577],
       [ 1.71644016,  0.41466377,  1.29151425,  0.78327957],
       [ 1.83846197, -0.29958961,  1.465066  ,  0.78327957],
       [-0.8460179 ,  1.12891715, -1.36961254, -1.19970668],
       [-0.96803971,  1.12891715, -1.42746312, -1.19970668],
       [-0.8460179 ,  1.84317052, -1.31176196, -1.19970668],
       [ 0.86228747, -0.53767407,  0.4816061 ,  0.38668232],
       [ 0.98430929, -0.29958961,  0.4816061 ,  0.12228415],
       [ 2.20452741, -0.06150515,  1.63861775,  1.17987682],
       [-1.21208334,  0.

In [17]:
X_test

array([[ 0.37420022, -0.53767407,  0.53945668, -0.00991493],
       [-0.96803971,  1.12891715, -1.25391137, -0.80310943],
       [-0.47995246,  1.60508607, -1.31176196, -1.33190577],
       [ 0.74026566, -0.77575853,  0.88656017,  0.91547865],
       [ 0.00813479,  2.31933944, -1.4853137 , -1.33190577],
       [ 0.74026566,  0.17657931,  1.00226134,  0.78327957],
       [ 2.57059285,  1.84317052,  1.52291658,  1.04767774],
       [ 1.71644016,  1.36700161,  1.34936483,  1.70867316],
       [-0.35793065, -1.72809637,  0.1345026 ,  0.12228415],
       [-0.8460179 ,  1.84317052, -1.25391137, -1.33190577],
       [-0.96803971,  0.65274823, -1.36961254, -1.33190577],
       [-0.47995246,  0.89083269, -1.19606079, -1.33190577],
       [ 1.1063311 ,  0.17657931,  0.53945668,  0.38668232],
       [-0.60197427,  1.60508607, -1.31176196, -1.33190577],
       [-0.11388702, -1.01384299, -0.15475031, -0.2743131 ],
       [-0.47995246,  0.89083269, -1.31176196, -1.0675076 ],
       [ 1.22835291, -0.

In [18]:
#Step 6: Training the Naive Bayes Classification model on the Training Set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [20]:
y_pred = classifier.predict(X_test) 
y_pred


array(['versicolor', 'setosa', 'setosa', 'virginica', 'setosa',
       'virginica', 'virginica', 'virginica', 'versicolor', 'setosa',
       'setosa', 'setosa', 'versicolor', 'setosa', 'versicolor', 'setosa',
       'virginica', 'virginica', 'versicolor', 'setosa', 'versicolor',
       'setosa', 'versicolor', 'virginica', 'versicolor', 'virginica',
       'virginica', 'virginica', 'setosa', 'versicolor'], dtype='<U10')

In [22]:
#Step 7: Confusion Matrix and Accuracy
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[11,  0,  0],
       [ 0,  9,  1],
       [ 0,  0,  9]])

In [23]:
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(y_test, y_pred))
Accuracy :  1.0

Accuracy :  0.9666666666666667


In [24]:
#Step 8: Comparing the Real Values with Predicted Values


df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
df

Real Values Predicted Values
0   versicolor       versicolor
1       setosa           setosa
2       setosa           setosa
3    virginica        virginica
4       setosa           setosa
5    virginica        virginica
6    virginica        virginica
7    virginica        virginica
8   versicolor       versicolor
9       setosa           setosa
10      setosa           setosa
11      setosa           setosa
12  versicolor       versicolor
13      setosa           setosa
14  versicolor       versicolor
15      setosa           setosa
16   virginica        virginica
17   virginica        virginica
18  versicolor       versicolor
19      setosa           setosa
20  versicolor       versicolor
21      setosa           setosa
22  versicolor       versicolor
23   virginica        virginica
24  versicolor       versicolor
25   virginica        virginica
26  versicolor        virginica
27   virginica        virginica
28      setosa           setosa
29  versicolor       versicolor