In [1]:
#Step 1: Importing the Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [2]:
#Step 2: Importing the dataset
dataset = pd.read_csv('https://raw.githubusercontent.com/mk-gurucharan/Classification/master/IrisDataset.csv')

In [3]:
#Step 3:Describe dataset,See dimention and Exlpore dataset
dataset.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [4]:
dataset.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
dataset.shape

(150, 5)

In [6]:
X = dataset.iloc[:,:4].values
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
y = dataset['species'].values
y


array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [8]:
#Step 4: Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [9]:
#Step 5: Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train

array([[-0.28058519, -0.11105638,  0.2132471 ,  0.16481796],
       [-1.62251436, -1.69219801, -1.39688831, -1.19919275],
       [ 0.57336973,  0.79245313,  1.07581964,  1.66522974],
       [ 0.57336973,  0.56657575,  0.55827612,  0.57402117],
       [-0.89055299,  0.79245313, -1.28187864, -1.33559382],
       [ 0.57336973, -0.7886885 ,  0.67328579,  0.84682331],
       [-0.28058519, -1.24044326,  0.09823743, -0.10798418],
       [ 0.20738905, -0.33693375,  0.44326644,  0.4376201 ],
       [ 0.81735686, -0.11105638,  0.8458003 ,  1.11962546],
       [-0.28058519, -0.11105638,  0.44326644,  0.4376201 ],
       [-1.01254655, -1.69219801, -0.24679159, -0.24438525],
       [ 0.81735686, -0.56281113,  0.50077128,  0.4376201 ],
       [ 0.57336973, -0.56281113,  0.78829546,  0.4376201 ],
       [-0.15859163, -1.01456588, -0.13178192, -0.24438525],
       [ 0.6953633 , -0.56281113,  1.07581964,  1.25602653],
       [-0.03659807, -1.01456588,  0.15574226,  0.02841689],
       [ 0.32938261, -0.

In [10]:
X_test

array([[-0.40257875,  1.0183305 , -1.39688831, -1.33559382],
       [ 1.42732466,  0.34069838,  0.55827612,  0.30121903],
       [ 0.08539549, -0.11105638,  0.27075194,  0.4376201 ],
       [ 1.67131178,  0.34069838,  1.30583898,  0.84682331],
       [-1.13454011,  0.114821  , -1.28187864, -1.47199489],
       [-1.13454011,  0.114821  , -1.28187864, -1.47199489],
       [ 1.3053311 ,  0.114821  ,  0.78829546,  1.52882867],
       [ 0.08539549, -0.11105638,  0.78829546,  0.84682331],
       [ 0.32938261, -0.11105638,  0.50077128,  0.30121903],
       [ 0.57336973, -1.24044326,  0.73079062,  0.98322439],
       [ 2.15928602, -0.11105638,  1.650868  ,  1.25602653],
       [-1.86650148, -0.11105638, -1.51189798, -1.47199489],
       [-0.03659807, -0.7886885 ,  0.78829546,  0.98322439],
       [ 1.06134398,  0.114821  ,  1.07581964,  1.66522974],
       [ 0.6953633 ,  0.34069838,  0.90330513,  1.52882867],
       [-1.13454011, -1.24044326,  0.44326644,  0.71042224],
       [-0.03659807, -0.

In [11]:
#Step 6: Training the Naive Bayes Classification model on the Training Set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [12]:
y_pred = classifier.predict(X_test) 
y_pred


array(['setosa', 'versicolor', 'versicolor', 'virginica', 'setosa',
       'setosa', 'virginica', 'virginica', 'versicolor', 'virginica',
       'virginica', 'setosa', 'virginica', 'virginica', 'virginica',
       'versicolor', 'virginica', 'virginica', 'setosa', 'setosa',
       'virginica', 'versicolor', 'setosa', 'setosa', 'setosa',
       'virginica', 'virginica', 'setosa', 'versicolor', 'versicolor'],
      dtype='<U10')

In [13]:
#Step 7: Confusion Matrix and Accuracy
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[10,  0,  0],
       [ 0,  6,  0],
       [ 0,  1, 13]])

In [14]:
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(y_test, y_pred))
Accuracy :  1.0

Accuracy :  0.9666666666666667


In [15]:
#Step 8: Comparing the Real Values with Predicted Values


df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
df

Real Values Predicted Values
0       setosa           setosa
1   versicolor       versicolor
2   versicolor       versicolor
3    virginica        virginica
4       setosa           setosa
5       setosa           setosa
6    virginica        virginica
7    virginica        virginica
8   versicolor       versicolor
9    virginica        virginica
10   virginica        virginica
11      setosa           setosa
12   virginica        virginica
13   virginica        virginica
14   virginica        virginica
15   virginica       versicolor
16   virginica        virginica
17   virginica        virginica
18      setosa           setosa
19      setosa           setosa
20   virginica        virginica
21  versicolor       versicolor
22      setosa           setosa
23      setosa           setosa
24      setosa           setosa
25   virginica        virginica
26   virginica        virginica
27      setosa           setosa
28  versicolor       versicolor
29  versicolor       versicolor

In [17]:
from sklearn.metrics import accuracy_score, precision_score, recall_score

# Calculate metrics
accuracy = accuracy_score(y_test, y_pred)
error_rate = 1 - accuracy
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')

# Print metrics
print("Confusion Matrix:\n", cm)
print(f"Accuracy: {accuracy:.2f}")
print(f"Error Rate: {error_rate:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")

Confusion Matrix:
 [[10  0  0]
 [ 0  6  0]
 [ 0  1 13]]
Accuracy: 0.97
Error Rate: 0.03
Precision: 0.97
Recall: 0.97
